jobs:
- job: DockerBuild
  pool:
    vmImage: ubuntu-18.04
  variables:
    DOCKER_BUILDKIT: 1
  # TODO: Add caching.
  steps:
  - checkout: self
    fetchDepth: 1
    submodules: false

  - task: ShellScript@2
    inputs:
      scriptPath: scripts/docker_build.sh
