jobs:
- job: StaticAnalysis
  pool:
    vmImage: ubuntu-18.04
  steps:
  - checkout: self
    fetchDepth: 1
    submodules: false

  - task: Cache@2
    inputs:
      key: '"$(Agent.OS)" | detekt | gradle-caches | gradle.properties, settings.gradle.kts, **/build.gradle.kts'
      restoreKeys: |
        "$(Agent.OS)" | detekt | gradle-caches
      path: $(GRADLE_USER_HOME)/caches
    displayName: Cache Gradle Caches

  - task: Cache@2
    inputs:
      key: '"$(Agent.OS)" | gradle-wrapper | gradle/wrapper/gradle-wrapper.properties'
      restoreKeys: |
        "$(Agent.OS)" | gradle-wrapper
      path: $(GRADLE_USER_HOME)/wrapper/dists
    displayName: Cache Gradle Wrapper

  - task: Gradle@2
    displayName: Detekt
    inputs:
      gradleWrapperFile: gradlew
      options: --no-daemon --stacktrace --scan
      tasks: detekt
      javaHomeOption: JDKVersion
      jdkVersionOption: 1.11
      gradleOptions: -Xmx8192m

  - task: UsePythonVersion@0
    displayName: Enable Python 3.6
    inputs:
      versionSpec: 3.6
      addToPath: true
      architecture: x64

  - bash: |
      pip install --user reuse
      ~/.local/bin/reuse lint
    displayName: Check REUSE Compliance

  # Ensure that any running Gradle daemon is stopped before caching starts.
  - bash: ./gradlew --stop
    displayName: Stop Gradle Daemon
