name: Automatic Rebase

on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    if: github.event.issue.pull_request != null && github.event.comment.body == '/rebase'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Rebase Branch
      uses: docker://cirrusactions/rebase:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
